name: Update package version

on:
  workflow_dispatch:
    inputs:
      version-increment-type:
        description: "What would you like to increment? Major, minor or patch?"
        required: true
        default: "review"
        type: choice
        options:
          - major
          - minor
          - patch
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: "yarn"
      - name: Test
        run: |
          git log
          git config user.name 'GHA Workflow'
          git config user.email '-'
          npm version ${{ github.event.inputs.version-increment-type }}
          git log
